// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvvqpyvrzojjoekfueug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2dnFweXZyem9qam9la2Z1ZXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzIwMTksImV4cCI6MjA2NDgwODAxOX0.naRwd_tU-0UAsyu2sWLdxyhCk_-D-41zJqii44H9R9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);